version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: install additional packages
          command: sudo apt-get update && sudo apt-get install tree
      - run:
          name: install sdkman
          command: curl -s "https://get.sdkman.io" | bash && source ~/.sdkman/bin/sdkman-init.sh
      - run:
          name: show content of home directory
          command: tree -a ~
      - run:
          name: show Version of sdkman
          command: cat ~/.bashrc && sdk version
      - checkout
      - run:
          name: Build and Test
          command: mvn -B package
workflows:
  version: 2.1
  build:
    jobs:
      - build