version: 2.1

defaults: &defaults
  machine:
    image: ubuntu-1604:201903-01

jobs:
  build:
    <<: *defaults

    steps:
      - run: wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -
      - run: sudo apt-get install -y software-properties-common
      - run: sudo add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
      - run: sudo apt-get update && sudo apt-get install adoptopenjdk-11-openj9 tree graphviz
      - checkout
      - run:
          name: Build and Test
          command: mvn -B package
workflows:
  version: 2.1
  build:
    jobs:
      - build