version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Install sdkman
          command: curl -s "https://get.sdkman.io" | bash
      - run:
          name: Show Version of sdkman
          command: sdk -version
      - checkout
      - run:
          name: Build and Test
          command: mvn -B package
workflows:
  version: 2.1
  build:
    jobs:
      - build